version: '3'

services:

  web:
    build:
      context: ./images
      dockerfile: web.Dockerfile
    command: npm run dev
    volumes:
      - ./server:/usr/app
    ports:
      - 5000:5000
    environment: 
      PORT: 5000
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DBNAME: ${MONGO_DBNAME}
  
  mongo:
    build:
      context: ./images
      dockerfile: db.Dockerfile
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}

  mongo-express:
    image: mongo-express
#    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: 'mongo'
    depends_on:
      - mongo

